/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketing;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

public class BusRoute extends javax.swing.JFrame {
        JTransit jTransit;
        public boolean discountStudent = false;

        public BusRoute() {
            setUI();
            initComponents();
        }
        public BusRoute(JTransit jTransit) {
            this.jTransit = jTransit;
            initComponents();
        }
        private void setUI() {
            UIManager.put("OptionPane.background", new ColorUIResource(46, 72, 187));
            UIManager.put("Panel.background", new ColorUIResource(46, 72, 187));
            UIManager.put("OptionPane.messageForeground", new ColorUIResource(246, 247, 252));
            UIManager.put("Button.background", new Color(246, 247, 252));
            UIManager.put("Button.foreground", new Color(46, 72, 187));
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        TO = new javax.swing.JLabel();
        FROM1 = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        name1 = new javax.swing.JLabel();
        subname1 = new javax.swing.JLabel();
        discount = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Bus Routes");
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(20, 31, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aftika ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUS ROUTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 250, 36));

        options.setFont(new java.awt.Font("Aftika Light", 0, 14)); // NOI18N
        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cubao", "TIPQC", "J.P Rizal", "Katipunan Ave.", "SM Marikina", "Ligaya", "Sta. Lucia Mall" }));
        options.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                optionsComponentRemoved(evt);
            }
        });
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        jPanel1.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 150, 30));

        confirm.setBackground(new java.awt.Color(46, 72, 187));
        confirm.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 107, 50));

        back.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(20, 31, 80));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 107, 50));

        TO.setFont(new java.awt.Font("Aftika SemiBold", 0, 18)); // NOI18N
        TO.setForeground(new java.awt.Color(255, 255, 255));
        TO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TO.setText("TO:");
        jPanel1.add(TO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 60, 30));

        FROM1.setFont(new java.awt.Font("Aftika SemiBold", 0, 18)); // NOI18N
        FROM1.setForeground(new java.awt.Color(255, 255, 255));
        FROM1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FROM1.setText("FROM:");
        jPanel1.add(FROM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 30));

        destination.setFont(new java.awt.Font("Aftika Light", 0, 14)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sta. Lucia Mall", "Ligaya", "SM Marikina", "Katipunan Ave.", "J.P Rizal", "TIPQC", "Cubao" }));
        destination.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                destinationComponentRemoved(evt);
            }
        });
        destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationActionPerformed(evt);
            }
        });
        jPanel1.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, 30));

        name1.setFont(new java.awt.Font("Akira Expanded", 2, 48)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("JTransit");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 46));

        subname1.setFont(new java.awt.Font("Aftika Light", 0, 16)); // NOI18N
        subname1.setForeground(new java.awt.Color(255, 255, 255));
        subname1.setText("Bus Ticketing System");
        jPanel1.add(subname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        discount.setBackground(new java.awt.Color(20, 31, 80));
        discount.setFont(new java.awt.Font("Aftika SemiBold", 0, 14)); // NOI18N
        discount.setForeground(new java.awt.Color(255, 255, 255));
        discount.setText("Student");
        discount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                discountStateChanged(evt);
            }
        });
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationActionPerformed

    private void destinationComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_destinationComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationComponentRemoved

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    
    this.jTransit.setVisible(true);
    dispose();
     
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
    int selectedOption = options.getSelectedIndex();
    int selectedDestination = destination.getSelectedIndex();

    double price = 0;
    boolean error = false;

    ImageIcon userIcon = new ImageIcon(getClass().getResource("/assets/logo_1.png"));

    String from = options.getSelectedItem().toString();
    String to = destination.getSelectedItem().toString();

    switch (selectedOption) {
    case 0:
        switch (selectedDestination) {
        case 0:
            price = 15.25;
            break;
        case 1:
            price = 14.00;
            break;
        case 2:
            price = 14.00;
            break;
        case 3:
            price = 13.00;
            break;
        case 4:
            price = 13.00;
            break;
        case 5:
            price = 12.00;
            break;
        case 6:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        }
        break;
    case 1:
        switch (selectedDestination) {
        case 0:
            price = 14.00;
            break;
        case 1:
            price = 14.00;
            break;
        case 2:
            price = 13.00;
            break;
        case 3:
            price = 12.00;
            break;
        case 4:
            price = 12.00;
            break;
        case 5:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 6:
            price = 12.00;
            break;
        }
        break;
    case 2:
        switch (selectedDestination) {
        case 0:
            price = 14.00;
            break;
        case 1:
            price = 13.00;
            break;
        case 2:
            price = 12.00;
            break;
        case 3:
            price = 12.00;
            break;
        case 4:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 5:
            price = 12.00;
            break;
        case 6:
            price = 13.00;
            break;
        }
        break;
    case 3:
        switch (selectedDestination) {
        case 0:
            price = 13.00;
            break;
        case 1:
            price = 13.00;
            break;
        case 2:
            price = 12.00;
            break;
        case 3:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 4:
            price = 12.00;
            break;
        case 5:
            price = 12.00;
            break;
        case 6:
            price = 13.00;
            break;
        }
        break;
    case 4:
        switch (selectedDestination) {
        case 0:
            price = 12.00;
            break;
        case 1:
            price = 13.00;
            break;
        case 2:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 3:
            price = 12.00;
            break;
        case 4:
            price = 12.00;
            break;
        case 5:
            price = 13.00;
            break;
        case 6:
            price = 13.00;
            break;
        }
        break;
    case 5:
        switch (selectedDestination) {
        case 0:
            price = 12.00;
            break;
        case 1:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 2:
            price = 13.00;
            break;
        case 3:
            price = 13.00;
            break;
        case 4:
            price = 13.00;
            break;
        case 5:
            price = 14.00;
            break;
        case 6:
            price = 15.25;
            break;
        }
        break;
    case 6:
        switch (selectedDestination) {
        case 0:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 1:
            price = 12.00;
            break;
        case 2:
            price = 13.00;
            break;
        case 3:
            price = 13.00;
            break;
        case 4:
            price = 14.00;
            break;
        case 5:
            price = 14.00;
            break;
        case 6:
            price = 15.25;
            break;
        }
        break;
    }
    if(discount.isSelected()){
        price *= 0.8;
    }
    if (!error) {
        BusDetails busDetails = new BusDetails(price, from, to, this.jTransit, this);
        busDetails.setVisible(true);

        this.setVisible(false);
    }
    }//GEN-LAST:event_confirmActionPerformed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsActionPerformed

    private void optionsComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_optionsComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsComponentRemoved

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed

    }//GEN-LAST:event_discountActionPerformed

    private void discountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_discountStateChanged
    if (discount.isSelected()){
       discountStudent = true;
    }else {
        discountStudent = false;
    }
    }//GEN-LAST:event_discountStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusRoute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FROM1;
    private javax.swing.JLabel TO;
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JCheckBox discount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name1;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JLabel subname1;
    // End of variables declaration//GEN-END:variables
}
