/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketing;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;

public class BusRoute extends javax.swing.JFrame {
        JTransit jTransit;
        public boolean discountStudent = false;

        public BusRoute() {
            setUI();
            initComponents();
        }
        public BusRoute(JTransit jTransit) {
            this.jTransit = jTransit;
            initComponents();
        }
        private void setUI() {
            UIManager.put("OptionPane.background", new ColorUIResource(46, 72, 187));
            UIManager.put("Panel.background", new ColorUIResource(46, 72, 187));
            UIManager.put("OptionPane.messageForeground", new ColorUIResource(246, 247, 252));
            UIManager.put("Button.background", new Color(246, 247, 252));
            UIManager.put("Button.foreground", new Color(46, 72, 187));
            UIManager.put("ToggleButton.select", Color.RED);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        TO = new javax.swing.JLabel();
        FROM1 = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        name1 = new javax.swing.JLabel();
        subname1 = new javax.swing.JLabel();
        discount = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Bus Routes");
        setBackground(new java.awt.Color(153, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 31, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aftika ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIYAHE ROUTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 310, 36));

        options.setBackground(new java.awt.Color(251, 251, 253));
        options.setFont(new java.awt.Font("Aftika Light", 0, 14)); // NOI18N
        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SM Aura", "Kalayaan Ave.", "Bagong Ilog", "Lanuza Ave.", "Hypermarket", "Ortigas Ave.", "Wilcon Depot", "Eastwood", "Libis", "IVC Flyover", "SM Marikina", "Ligaya", "Sta. Lucia", "Vermont", "SM Masinag", "Maries Village", "SM Cherry Antipolo", "Pagrai", "Cogeo Gate 1", "Northville", "Cogeo Gate 2" }));
        options.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                optionsComponentRemoved(evt);
            }
        });
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        jPanel1.add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 150, 30));

        confirm.setBackground(new java.awt.Color(46, 72, 187));
        confirm.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 50));

        back.setBackground(new java.awt.Color(246, 247, 252));
        back.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(20, 31, 80));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 120, 50));

        TO.setFont(new java.awt.Font("Aftika SemiBold", 0, 18)); // NOI18N
        TO.setForeground(new java.awt.Color(255, 255, 255));
        TO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TO.setText("TO:");
        jPanel1.add(TO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 60, 30));

        FROM1.setFont(new java.awt.Font("Aftika SemiBold", 0, 18)); // NOI18N
        FROM1.setForeground(new java.awt.Color(255, 255, 255));
        FROM1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FROM1.setText("FROM:");
        jPanel1.add(FROM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 30));

        destination.setBackground(new java.awt.Color(251, 251, 253));
        destination.setFont(new java.awt.Font("Aftika Light", 0, 14)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cogeo Gate 2", "Northville", "Cogeo Gate 1", "Pagrai", "SM Cherry Antipolo", "Maries Village", "SM Masinag", "Vermont", "Sta. Lucia", "Ligaya", "SM Marikina", "IVC Flyover", "Libis", "Eastwood", "Wilcon Depot", "Ortigas Ave.", "Hypermarket", "Lanuza Ave.", "Bagong Ilog", "Kalayaan Ave.", "SM Aura" }));
        destination.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                destinationComponentRemoved(evt);
            }
        });
        destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationActionPerformed(evt);
            }
        });
        jPanel1.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 150, 30));

        name1.setFont(new java.awt.Font("Akira Expanded", 2, 48)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("JTransit");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 46));

        subname1.setFont(new java.awt.Font("Aftika Light", 0, 16)); // NOI18N
        subname1.setForeground(new java.awt.Color(255, 255, 255));
        subname1.setText("Bus Ticketing System");
        jPanel1.add(subname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        discount.setBackground(new java.awt.Color(20, 31, 80));
        discount.setFont(new java.awt.Font("Aftika SemiBold", 0, 11)); // NOI18N
        discount.setForeground(new java.awt.Color(255, 255, 255));
        discount.setText("STUDENT");
        discount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                discountStateChanged(evt);
            }
        });
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationActionPerformed

    private void destinationComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_destinationComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationComponentRemoved

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    
    this.jTransit.setVisible(true);
    dispose();
     
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
    int selectedOption = options.getSelectedIndex();
    int selectedDestination = destination.getSelectedIndex();

    double price = 0;
    boolean error = false;

    ImageIcon userIcon = new ImageIcon(getClass().getResource("/assets/logo_1.png"));

    String from = options.getSelectedItem().toString();
    String to = destination.getSelectedItem().toString();

    switch (selectedOption) {
    case 0:
        switch (selectedDestination) {
        case 0:
            price = 43.00;
            break;
        case 1:
            price = 41.00;
            break;
        case 2:
            price = 39.00;
            break;
        case 3:
            price = 37.00;
            break;
        case 4:
            price = 35.00;
            break;
        case 5:
            price = 33.00;
            break;
        case 6:
            price = 31.00;
            break;
        case 7:
            price = 29.00;
            break;
        case 8:
            price = 27.00;
            break;
        case 9:
            price = 25.00;
            break;
        case 10:
            price = 23.00;
            break;
        case 11: 
            price = 21.00;
            break;
        case 12:
            price = 19.00;
            break;
        case 13:
            price = 17.00;
            break;
        case 14:
            price = 15.00;
            break;
        case 15:
            price = 13.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            price = 11.00;
            break;
        case 19:
            price = 11.00;
            break;
        case 20:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        }
        break;
    case 1:
        switch (selectedDestination) {
        case 0:
            price = 41.00;
            break;
        case 1:
            price = 39.00;
            break;
        case 2:
            price = 37.00;
            break;
        case 3:
            price = 35.00;
            break;
        case 4:
            price = 33.00;
            break;
        case 5:
            price = 31.00;
            break;
        case 6:
            price = 29.00;
            break;
        case 7:
            price = 27.00;
            break;
        case 8:
            price = 25.00;
            break;
        case 9:
            price = 23.00;
            break;
        case 10:
            price = 21.00;
            break;
        case 11: 
            price = 19.00;
            break;
        case 12:
            price = 17.00;
            break;
        case 13:
            price = 15.00;
            break;
        case 14:
            price = 13.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            price = 11.00;
            break;
        case 19:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 20:
            price = 11.00;
            break;
        }
        break;
    case 2:
        switch (selectedDestination) {
        case 0:
            price = 39.00;
            break;
        case 1:
            price = 37.00;
            break;
        case 2:
            price = 35.00;
            break;
        case 3:
            price = 33.00;
            break;
        case 4:
            price = 31.00;
            break;
        case 5:
            price = 29.00;
            break;
        case 6:
            price = 27.00;
            break;
        case 7:
            price = 25.00;
            break;
        case 8:
            price = 23.00;
            break;
        case 9:
            price = 21.00;
            break;
        case 10:
            price = 19.00;
            break;
        case 11: 
            price = 17.00;
            break;
        case 12:
            price = 15.00;
            break;
        case 13:
            price = 13.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 19:
            price = 11.00;
            break;
        case 20:
            price = 11.00;
            break;
        }
        break;
    case 3:
        switch (selectedDestination) {
        case 0:
            price = 37.00;
            break;
        case 1:
            price = 35.00;
            break;
        case 2:
            price = 33.00;
            break;
        case 3:
            price = 31.00;
            break;
        case 4:
            price = 29.00;
            break;
        case 5:
            price = 27.00;
            break;
        case 6:
            price = 25.00;
            break;
        case 7:
            price = 23.00;
            break;
        case 8:
            price = 21.00;
            break;
        case 9:
            price = 19.00;
            break;
        case 10:
            price = 17.00;
            break;
        case 11: 
            price = 15.00;
            break;
        case 12:
            price = 13.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 18:
            price = 11.00;
            break;
        case 19:
            price = 11.00;
            break;
        case 20:
            price = 11.00;
            break;
        }
        break;
    case 4:
        switch (selectedDestination) {
        case 0:
            price = 35.00;
            break;
        case 1:
            price = 33.00;
            break;
        case 2:
            price = 31.00;
            break;
        case 3:
            price = 29.00;
            break;
        case 4:
            price = 27.00;
            break;
        case 5:
            price = 25.00;
            break;
        case 6:
            price = 23.00;
            break;
        case 7:
            price = 21.00;
            break;
        case 8:
            price = 19.00;
            break;
        case 9:
            price = 17.00;
            break;
        case 10:
            price = 15.00;
            break;
        case 11: 
            price = 13.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            price = 11.00;
            break;
        case 19:
            price = 11.00;
            break;
        case 20:
            price = 11.00;
            break;
        }
        break;
    case 5:
        switch (selectedDestination) {
        case 0:
            price = 33.00;
            break;
        case 1:
            price = 31.00;
            break;
        case 2:
            price = 29.00;
            break;
        case 3:
            price = 27.00;
            break;
        case 4:
            price = 25.00;
            break;
        case 5:
            price = 23.00;
            break;
        case 6:
            price = 21.00;
            break;
        case 7:
            price = 19.00;
            break;
        case 8:
            price = 17.00;
            break;
        case 9:
            price = 15.00;
            break;
        case 10:
            price = 13.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            price = 11.00;
            break;
        case 19:
            price = 11.00;
            break;
        case 20:
            price = 13.00;
            break;
        }
        break;
    case 6:
        switch (selectedDestination) {
        case 0:
            price = 31.00;
            break;
        case 1:
            price = 29.00;
            break;
        case 2:
            price = 27.00;
            break;
        case 3:
            price = 25.00;
            break;
        case 4:
            price = 23.00;
            break;
        case 5:
            price = 21.00;
            break;
        case 6:
            price = 19.00;
            break;
        case 7:
            price = 17.00;
            break;
        case 8:
            price = 15.00;
            break;
        case 9:
            price = 13.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            price = 11.00;
            break;
        case 19:
            price = 13.00;
            break;
        case 20:
            price = 15.00;
            break;
        }
        break;
    case 7:
        switch (selectedDestination) {
        case 0:
            price = 29.00;
            break;
        case 1:
            price = 27.00;
            break;
        case 2:
            price = 25.00;
            break;
        case 3:
            price = 23.00;
            break;
        case 4:
            price = 21.00;
            break;
        case 5:
            price = 19.00;
            break;
        case 6:
            price = 17.00;
            break;
        case 7:
            price = 15.00;
            break;
        case 8:
            price = 13.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 11.00;
            break;
        case 18:
            price = 13.00;
            break;
        case 19:
            price = 15.00;
            break;
        case 20:
            price = 17.00;
            break;
        }break;
    case 8:
        switch (selectedDestination) {
        case 0:
            price = 27.00;
            break;
        case 1:
            price = 25.00;
            break;
        case 2:
            price = 23.00;
            break;
        case 3:
            price = 21.00;
            break;
        case 4:
            price = 19.00;
            break;
        case 5:
            price = 17.00;
            break;
        case 6:
            price = 15.00;
            break;
        case 7:
            price = 13.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 11.00;
            break;
        case 17:
            price = 13.00;
            break;
        case 18:
            price = 15.00;
            break;
        case 19:
            price = 17.00;
            break;
        case 20:
            price = 19.00;
            break;
        }break;
    case 9:
        switch (selectedDestination) {
        case 0:
            price = 25.00;
            break;
        case 1:
            price = 23.00;
            break;
        case 2:
            price = 21.00;
            break;
        case 3:
            price = 19.00;
            break;
        case 4:
            price = 17.00;
            break;
        case 5:
            price = 15.00;
            break;
        case 6:
            price = 13.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 11.00;
            break;
        case 16: 
            price = 13.00;
            break;
        case 17:
            price = 15.00;
            break;
        case 18:
            price = 17.00;
            break;
        case 19:
            price = 19.00;
            break;
        case 20:
            price = 21.00;
            break;
        }break;
    case 10:
        switch (selectedDestination) {
        case 0:
            price = 23.00;
            break;
        case 1:
            price = 21.00;
            break;
        case 2:
            price = 19.00;
            break;
        case 3:
            price = 17.00;
            break;
        case 4:
            price = 15.00;
            break;
        case 5:
            price = 13.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 11.00;
            break;
        case 15:
            price = 13.00;
            break;
        case 16: 
            price = 15.00;
            break;
        case 17:
            price = 17.00;
            break;
        case 18:
            price = 19.00;
            break;
        case 19:
            price = 21.00;
            break;
        case 20:
            price = 23.00;
            break;
        }break;
    case 11:
        switch (selectedDestination) {
        case 0:
            price = 21.00;
            break;
        case 1:
            price = 19.00;
            break;
        case 2:
            price = 17.00;
            break;
        case 3:
            price = 15.00;
            break;
        case 4:
            price = 13.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 11.00;
            break;
        case 14:
            price = 13.00;
            break;
        case 15:
            price = 15.00;
            break;
        case 16: 
            price = 17.00;
            break;
        case 17:
            price = 19.00;
            break;
        case 18:
            price = 21.00;
            break;
        case 19:
            price = 23.00;
            break;
        case 20:
            price = 25.00;
            break;
        }break;
    case 12:
        switch (selectedDestination) {
        case 0:
            price = 19.00;
            break;
        case 1:
            price = 17.00;
            break;
        case 2:
            price = 15.00;
            break;
        case 3:
            price = 13.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 11.00;
            break;
        case 13:
            price = 13.00;
            break;
        case 14:
            price = 15.00;
            break;
        case 15:
            price = 17.00;
            break;
        case 16: 
            price = 19.00;
            break;
        case 17:
            price = 21.00;
            break;
        case 18:
            price = 23.00;
            break;
        case 19:
            price = 25.00;
            break;
        case 20:
            price = 27.00;
            break;
        }break;
    case 13:
        switch (selectedDestination) {
        case 0:
            price = 17.00;
            break;
        case 1:
            price = 15.00;
            break;
        case 2:
            price = 13.00;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 11.00;
            break;
        case 12:
            price = 13.00;
            break;
        case 13:
            price = 15.00;
            break;
        case 14:
            price = 17.00;
            break;
        case 15:
            price = 19.00;
            break;
        case 16: 
            price = 21.00;
            break;
        case 17:
            price = 23.00;
            break;
        case 18:
            price = 25.00;
            break;
        case 19:
            price = 27.00;
            break;
        case 20:
            price = 29.00;
            break;
        }break;
    case 14:
        switch (selectedDestination) {
        case 0:
            price = 15.00;
            break;
        case 1:
            price = 13.00;
            break;
        case 2:
            price = 11.00;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 11.00;
            break;
        case 11: 
            price = 13.00;
            break;
        case 12:
            price = 15.00;
            break;
        case 13:
            price = 17.00;
            break;
        case 14:
            price = 19.00;
            break;
        case 15:
            price = 21.00;
            break;
        case 16: 
            price = 23.00;
            break;
        case 17:
            price = 25.00;
            break;
        case 18:
            price = 27.00;
            break;
        case 19:
            price = 29.00;
            break;
        case 20:
            price = 31.00;
            break;
        }break;
    case 15:
        switch (selectedDestination) {
        case 0:
            price = 13.00;
            break;
        case 1:
            price = 11.00;
            break;
        case 2:
            price = 11.00;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 11.00;
            break;
        case 10:
            price = 13.00;
            break;
        case 11: 
            price = 15.00;
            break;
        case 12:
            price = 17.00;
            break;
        case 13:
            price = 19.00;
            break;
        case 14:
            price = 21.00;
            break;
        case 15:
            price = 23.00;
            break;
        case 16: 
            price = 25.00;
            break;
        case 17:
            price = 27.00;
            break;
        case 18:
            price = 29.00;
            break;
        case 19:
            price = 31.00;
            break;
        case 20:
            price = 33.00;
            break;
        }break;
    case 16:
        switch (selectedDestination) {
        case 0:
            price = 11.00;
            break;
        case 1:
            price = 11.00;
            break;
        case 2:
            price = 11.00;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 11.00;
            break;
        case 9:
            price = 13.00;
            break;
        case 10:
            price = 15.00;
            break;
        case 11: 
            price = 17.00;
            break;
        case 12:
            price = 19.00;
            break;
        case 13:
            price = 21.00;
            break;
        case 14:
            price = 23.00;
            break;
        case 15:
            price = 25.00;
            break;
        case 16: 
            price = 27.00;
            break;
        case 17:
            price = 29.00;
            break;
        case 18:
            price = 31.00;
            break;
        case 19:
            price = 33.00;
            break;
        case 20:
            price = 35.00;
            break;
        }break;
    case 17:
        switch (selectedDestination) {
        case 0:
            price = 11.00;
            break;
        case 1:
            price = 11.00;
            break;
        case 2:
            price = 11.00;
            break;
        case 3:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 11.00;
            break;
        case 8:
            price = 13.00;
            break;
        case 9:
            price = 15.00;
            break;
        case 10:
            price = 17.00;
            break;
        case 11: 
            price = 19.00;
            break;
        case 12:
            price = 21.00;
            break;
        case 13:
            price = 23.00;
            break;
        case 14:
            price = 25.00;
            break;
        case 15:
            price = 27.00;
            break;
        case 16: 
            price = 29.00;
            break;
        case 17:
            price = 31.00;
            break;
        case 18:
            price = 33.00;
            break;
        case 19:
            price = 35.00;
            break;
        case 20:
            price = 37.00;
            break;
        }break;
    case 18:
        switch (selectedDestination) {
        case 0:
            price = 11.00;
            break;
        case 1:
            price = 11.00;
            break;
        case 2:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 11.00;
            break;
        case 7:
            price = 13.00;
            break;
        case 8:
            price = 15.00;
            break;
        case 9:
            price = 17.00;
            break;
        case 10:
            price = 19.00;
            break;
        case 11: 
            price = 21.00;
            break;
        case 12:
            price = 23.00;
            break;
        case 13:
            price = 25.00;
            break;
        case 14:
            price = 27.00;
            break;
        case 15:
            price = 29.00;
            break;
        case 16: 
            price = 31.00;
            break;
        case 17:
            price = 33.00;
            break;
        case 18:
            price = 35.00;
            break;
        case 19:
            price = 37.00;
            break;
        case 20:
            price = 39.00;
            break;
        }break;
    case 19:
        switch (selectedDestination) {
        case 0:
            price = 11.00;
            break;
        case 1:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 2:
            price = 11.00;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 11.00;
            break;
        case 6:
            price = 13.00;
            break;
        case 7:
            price = 15.00;
            break;
        case 8:
            price = 17.00;
            break;
        case 9:
            price = 19.00;
            break;
        case 10:
            price = 21.00;
            break;
        case 11: 
            price = 23.00;
            break;
        case 12:
            price = 25.00;
            break;
        case 13:
            price = 27.00;
            break;
        case 14:
            price = 29.00;
            break;
        case 15:
            price = 31.00;
            break;
        case 16: 
            price = 33.00;
            break;
        case 17:
            price = 35.00;
            break;
        case 18:
            price = 37.00;
            break;
        case 19:
            price = 39.00;
            break;
        case 20:
            price = 41.00;
            break;
        }break;
    case 20:
        switch (selectedDestination) {
        case 0:
            JOptionPane.showMessageDialog(null, "Please select a valid destination.", "INVALID SELECTION", JOptionPane.ERROR_MESSAGE, userIcon);
            error = true;
            break;
        case 1:
            price = 11.00;
            break;
        case 2:
            price = 11.00;
            break;
        case 3:
            price = 11.00;
            break;
        case 4:
            price = 11.00;
            break;
        case 5:
            price = 13.00;
            break;
        case 6:
            price = 15.00;
            break;
        case 7:
            price = 17.00;
            break;
        case 8:
            price = 19.00;
            break;
        case 9:
            price = 21.00;
            break;
        case 10:
            price = 23.00;
            break;
        case 11: 
            price = 25.00;
            break;
        case 12:
            price = 27.00;
            break;
        case 13:
            price = 29.00;
            break;
        case 14:
            price = 31.00;
            break;
        case 15:
            price = 33.00;
            break;
        case 16: 
            price = 35.00;
            break;
        case 17:
            price = 37.00;
            break;
        case 18:
            price = 39.00;
            break;
        case 19:
            price = 41.00;
            break;
        case 20:
            price = 43.00;
            break;
        }break;
    }
    if(discount.isSelected()){
        price *= 0.8;
    }
    if (!error) {
        BusDetails busDetails = new BusDetails(price, from, to, this.jTransit, this);
        busDetails.setVisible(true);

        this.setVisible(false);
    }
    }//GEN-LAST:event_confirmActionPerformed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsActionPerformed

    private void optionsComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_optionsComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsComponentRemoved

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed

    }//GEN-LAST:event_discountActionPerformed

    private void discountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_discountStateChanged
        if (discount.isSelected()) {
           discountStudent = true;

        } else {
           discountStudent = false;
        }

    }//GEN-LAST:event_discountStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try{
          javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){
                System.out.println("UIManager Exception : "+e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusRoute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FROM1;
    private javax.swing.JLabel TO;
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JCheckBox discount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name1;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JLabel subname1;
    // End of variables declaration//GEN-END:variables
}
