/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketing;

import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;


public class SignUp extends javax.swing.JFrame {
    boolean validator;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ticketdetails = new javax.swing.JLabel();
        FROM2 = new javax.swing.JLabel();
        FROM3 = new javax.swing.JLabel();
        FROM4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        regName = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        regContact = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtUser = new javax.swing.JTextPane();
        txtPass = new javax.swing.JPasswordField();
        regPass = new javax.swing.JPasswordField();
        confirm = new javax.swing.JButton();
        FROM6 = new javax.swing.JLabel();
        FROM7 = new javax.swing.JLabel();
        FROM8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        match = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        FROM5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Account");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 31, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 247, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(736, 473));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticketdetails.setFont(new java.awt.Font("Aftika ExtraBold", 0, 36)); // NOI18N
        ticketdetails.setForeground(new java.awt.Color(20, 31, 80));
        ticketdetails.setText("SIGN UP");
        jPanel2.add(ticketdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        FROM2.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        FROM2.setForeground(new java.awt.Color(20, 31, 80));
        FROM2.setText("CONTACT NO.");
        jPanel2.add(FROM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 36));

        FROM3.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        FROM3.setForeground(new java.awt.Color(20, 31, 80));
        FROM3.setText("EMAIL:");
        jPanel2.add(FROM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 36));

        FROM4.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        FROM4.setForeground(new java.awt.Color(20, 31, 80));
        FROM4.setText("PASSWORD:");
        jPanel2.add(FROM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 36));

        regName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        regName.setFont(new java.awt.Font("Aftika Light", 0, 15)); // NOI18N
        regName.setForeground(new java.awt.Color(20, 31, 80));
        jScrollPane1.setViewportView(regName);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 30));

        regContact.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        regContact.setFont(new java.awt.Font("Aftika Light", 0, 15)); // NOI18N
        regContact.setForeground(new java.awt.Color(20, 31, 80));
        jScrollPane4.setViewportView(regContact);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 30));

        txtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUser.setFont(new java.awt.Font("Aftika Light", 0, 15)); // NOI18N
        txtUser.setForeground(new java.awt.Color(20, 31, 80));
        jScrollPane5.setViewportView(txtUser);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 30));

        txtPass.setFont(new java.awt.Font("Aftika Light", 0, 15)); // NOI18N
        txtPass.setForeground(new java.awt.Color(20, 31, 80));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 240, 30));

        regPass.setFont(new java.awt.Font("Aftika Light", 0, 15)); // NOI18N
        regPass.setForeground(new java.awt.Color(20, 31, 80));
        regPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPassActionPerformed(evt);
            }
        });
        jPanel2.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 30));

        confirm.setBackground(new java.awt.Color(46, 72, 187));
        confirm.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("CREATE ACCOUNT");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel2.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 40));

        FROM6.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        FROM6.setForeground(new java.awt.Color(20, 31, 80));
        FROM6.setText("NAME:");
        jPanel2.add(FROM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 36));

        FROM7.setFont(new java.awt.Font("Aftika Light", 0, 12)); // NOI18N
        FROM7.setForeground(new java.awt.Color(20, 31, 80));
        FROM7.setText("Already have an account?");
        jPanel2.add(FROM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        FROM8.setFont(new java.awt.Font("Aftika Bold", 0, 14)); // NOI18N
        FROM8.setForeground(new java.awt.Color(20, 31, 80));
        FROM8.setText("CONFIRM PASSWORD:");
        jPanel2.add(FROM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 190, 36));

        jButton1.setBackground(new java.awt.Color(246, 247, 252));
        jButton1.setFont(new java.awt.Font("Aftika SemiBold", 0, 12)); // NOI18N
        jButton1.setText("Login.");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 50, -1));

        match.setFont(new java.awt.Font("Aftika SemiBold", 2, 12)); // NOI18N
        match.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(match, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 200, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        name1.setFont(new java.awt.Font("Akira Expanded", 2, 48)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("JTransit");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        FROM5.setFont(new java.awt.Font("Aftika SemiBold", 0, 14)); // NOI18N
        FROM5.setForeground(new java.awt.Color(255, 255, 255));
        FROM5.setText("Start your journey with us.");
        jPanel1.add(FROM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 210, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/landing-page.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -10, 460, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

    String user = txtUser.getText();
    String regNameText = regName.getText();
    String regContactText = regContact.getText();
    String regPassText = new String(regPass.getPassword());
    String txtPassText = new String(txtPass.getPassword());
    
    ImageIcon userIcon = new ImageIcon(getClass().getResource("/assets/logo_1.png"));

    final String MESSAGE = "Please fill in all the required fields.";
    final String ERROR = "Passwords do not match. Please try again.";
    
    UIManager.put("OptionPane.background",new ColorUIResource(46,72,187));
    UIManager.put("Panel.background",new ColorUIResource(46,72,187));
    UIManager.put("OptionPane.messageForeground",new ColorUIResource(246,247,252));
    UIManager.put("Button.background",new Color(246,247,252));
    UIManager.put("Button.foreground",new Color(46,72,187));

    if (regNameText.equals("") || regContactText.equals("") || regPassText.equals("") || txtPassText.equals("") || user.equals("")) {
        JOptionPane.showMessageDialog(null, MESSAGE, "Error", JOptionPane.ERROR_MESSAGE, userIcon);
    } else if (!validator){
        JOptionPane.showMessageDialog(null, ERROR, "Error", JOptionPane.ERROR_MESSAGE, userIcon);
    }else {
        dispose();
        User bus = new User();
        bus.userLogin(user, regPassText, regContactText, regNameText);

        try {
            String st = "INSERT INTO users (email, name, password, contactNumber) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = BusTicketing.sqlConn.prepareStatement(st);

            pstmt.setString(1, user);
            pstmt.setString(2, regNameText);
            pstmt.setString(3, regPassText);
            pstmt.setString(4, regContactText);

            pstmt.executeUpdate();

            System.out.println("User added successfully");
        } catch (SQLException e) {
            System.out.println(e);
        }

    }
    
    
    }//GEN-LAST:event_confirmActionPerformed

    private void regPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         dispose();
         User bus = new User();  
         bus.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
    
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed

    }//GEN-LAST:event_txtPassKeyPressed

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped

    }//GEN-LAST:event_txtPassKeyTyped

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
    if (Arrays.equals(regPass.getPassword(), txtPass.getPassword())) {
      validator = true;
      
      match.setText("");
      regPass.setForeground(new Color(20, 31, 80));
      txtPass.setForeground(new Color(20, 31, 80));
    } else {
      validator = false;
      
      match.setText("Passwords do not match.");
      regPass.setForeground(new Color(208, 67, 76));
      txtPass.setForeground(new Color(208, 67, 76));
    }
    }//GEN-LAST:event_txtPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FROM2;
    private javax.swing.JLabel FROM3;
    private javax.swing.JLabel FROM4;
    private javax.swing.JLabel FROM5;
    private javax.swing.JLabel FROM6;
    private javax.swing.JLabel FROM7;
    private javax.swing.JLabel FROM8;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel match;
    private javax.swing.JLabel name1;
    private javax.swing.JTextPane regContact;
    private javax.swing.JTextPane regName;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JLabel ticketdetails;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextPane txtUser;
    // End of variables declaration//GEN-END:variables
}
