package busticketing;
import static busticketing.BusTicketing.sqlConn;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;


/**
 *
 * @author lathrell pagsuguiron
 */
public class User extends javax.swing.JFrame {
    String userName = "";
    String userPassword = "";
    String contactNumber = "";
    String fullName = "";
    
    boolean validator;

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        focus();
    }
    
    private void focus(){
        userPanel.requestFocus();
    }
    
    private void setUI() {
    UIManager.put("OptionPane.background", new ColorUIResource(46, 72, 187));
    UIManager.put("Panel.background", new ColorUIResource(46, 72, 187));
    UIManager.put("OptionPane.messageForeground", new ColorUIResource(246, 247, 252));
    UIManager.put("Button.background", new Color(246, 247, 252));
    UIManager.put("Button.foreground", new Color(46, 72, 187));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FROM7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ticketdetails = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        invalidCred = new javax.swing.JLabel();
        subname1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Authentication");
        setBackground(new java.awt.Color(51, 255, 0));
        setPreferredSize(new java.awt.Dimension(784, 502));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userPanel.setBackground(new java.awt.Color(246, 247, 252));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(20, 31, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(270, 470));
        jPanel2.setPreferredSize(new java.awt.Dimension(784, 502));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FROM7.setBackground(new java.awt.Color(246, 247, 252));
        FROM7.setFont(new java.awt.Font("Aftika Light", 0, 12)); // NOI18N
        FROM7.setForeground(new java.awt.Color(246, 247, 252));
        FROM7.setText("Don't have an account?");
        jPanel2.add(FROM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 20));

        jButton2.setBackground(new java.awt.Color(20, 31, 80));
        jButton2.setFont(new java.awt.Font("Aftika SemiBold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(246, 247, 252));
        jButton2.setText("Register.");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, 20));

        ticketdetails.setFont(new java.awt.Font("Aftika ExtraBold", 0, 36)); // NOI18N
        ticketdetails.setForeground(new java.awt.Color(255, 255, 255));
        ticketdetails.setText("LOGIN");
        jPanel2.add(ticketdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        uname.setFont(new java.awt.Font("Aftika Light", 0, 12)); // NOI18N
        uname.setForeground(new java.awt.Color(196, 197, 201));
        uname.setText("Email");
        uname.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unameFocusLost(evt);
            }
        });
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, 30));

        password.setFont(new java.awt.Font("Aftika Light", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(196, 197, 201));
        password.setText("Password");
        password.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        password.setEchoChar('\u0000');
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        showPass.setBackground(new java.awt.Color(20, 31, 80));
        showPass.setFont(new java.awt.Font("Aftika Light", 0, 12)); // NOI18N
        showPass.setForeground(new java.awt.Color(196, 197, 201));
        showPass.setText("Show Password");
        showPass.setBorder(null);
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel2.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        jButton1.setBackground(new java.awt.Color(46, 72, 187));
        jButton1.setFont(new java.awt.Font("Aftika SemiBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 31));

        invalidCred.setBackground(new java.awt.Color(255, 148, 148));
        invalidCred.setFont(new java.awt.Font("Aftika SemiBold", 2, 10)); // NOI18N
        invalidCred.setForeground(new java.awt.Color(255, 51, 51));
        invalidCred.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(invalidCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 240, 20));

        userPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        subname1.setFont(new java.awt.Font("Aftika SemiBold", 0, 14)); // NOI18N
        subname1.setForeground(new java.awt.Color(20, 31, 80));
        subname1.setText("Explore the world with ease!");
        userPanel.add(subname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        name1.setBackground(new java.awt.Color(20, 31, 80));
        name1.setFont(new java.awt.Font("Akira Expanded", 2, 48)); // NOI18N
        name1.setForeground(new java.awt.Color(20, 31, 80));
        name1.setText("JTransit");
        userPanel.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login-page.png"))); // NOI18N
        userPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -20, 510, 540));

        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 502));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void userLogin(String name, String password, String contact, String fName) {
        this.userName = name;
        this.userPassword = password;
        this.contactNumber = contact;
        this.fullName = fName;
        
        
        System.out.println("Name: " + userName);
        System.out.println("Password: " + userPassword);
        
        this.setVisible(true);
    }
    
    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
     
    }//GEN-LAST:event_unameActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = uname.getText();
        String pword = new String(password.getPassword());
        final String LOGIN_FAILURE_MESSAGE = "Invalid credentials.";

        ImageIcon userIcon = new ImageIcon(getClass().getResource("/assets/logo_1.png"));

        // Use a separate method to set the UI colors
        setUI();

        try (Statement statement = sqlConn.createStatement()) {
           ResultSet resultSet = statement.executeQuery("SELECT * FROM jtransit.users");

           while (resultSet.next()) {
              String emailFromDB = resultSet.getString("email");
              String passwordFromDB = resultSet.getString("password");

              if (email.equals(emailFromDB) && pword.equals(passwordFromDB)) {
                 this.userName = emailFromDB;
                 this.setVisible(false);
                 JTransit bus = new JTransit(this);
                 bus.setVisible(true);
                 return;
              } else if (email.equals(emailFromDB)) {
                 validator = false;

                 invalidCred.setText(LOGIN_FAILURE_MESSAGE);
                 return;
              } else if (!(email.equals(emailFromDB) && pword.equals(passwordFromDB))) {
                 validator = false;
                 invalidCred.setText("Incorrect username or password.");
              }
           }

           // Check for empty email and password fields separately
           if (email.equals("Email") || pword.equals("Password")) {
              JOptionPane.showMessageDialog(null, "Please fill in all the required fields.", "Error", JOptionPane.ERROR_MESSAGE, userIcon);
           }
        } catch (SQLException e) {
           System.out.print(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
    if (Arrays.equals(password.getPassword(), "Password".toCharArray())){
        password.setText("");
        password.setEchoChar('\u2022');
        password.setForeground(new Color(20, 31, 80));
    }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocusGained
    if (uname.getText().equals("Email")){
        uname.setText("");
        uname.setForeground(new Color(20, 31, 80));
       
    }
    }//GEN-LAST:event_unameFocusGained

    private void unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocusLost
    if (uname.getText().equals("")){
        uname.setText("Email");
        uname.setForeground(new java.awt.Color(196,197,201));
    }
    }//GEN-LAST:event_unameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
    if (Arrays.equals(password.getPassword(), "".toCharArray())){
        password.setText("Password");
        password.setEchoChar('\u0000');
        password.setForeground(new java.awt.Color(196,197,201));
    }
    }//GEN-LAST:event_passwordFocusLost

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
    if (showPass.isSelected()){
        password.setEchoChar((char)0);
    }
    else
        password.setEchoChar('*');
    }//GEN-LAST:event_showPassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        SignUp bus = new SignUp();
        bus.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased

    }//GEN-LAST:event_passwordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FROM7;
    private javax.swing.JLabel invalidCred;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name1;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JLabel subname1;
    private javax.swing.JLabel ticketdetails;
    private javax.swing.JTextField uname;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
